version: 2

jobs:
  build:
    docker:
      - image: continuumio/miniconda
    steps:
      - checkout
      - run:
          name: Conda config
          command: |
            conda config --set always_yes yes --set changeps1 no
      - run:
          name: Install dependencies
          command: |
            conda install -c conda-forge python-casacore
      - run:
          name: Setup .casarc
          command: ./setup_casarc.sh
      - run:
          name: Run test script
          command: python test.py
